fix for `nixos-rebild switch` where ${nixpkgs} would point to /nix/store instead of the nixpkgs
nixos-rebuild switch
building Nix...
building the system configuration...
error: getting status of '/nix/store/k8g2ma0sg58mzfjr1my8hys8gm374yqv-nixpkgs/nixos/lib/testing.nix': No such file or directory
(use '--show-trace' to show detailed location information)

and `/nix/store/k8g2ma0sg58mzfjr1my8hys8gm374yqv-nixpkgs` basically is /nix/store and not nixpkgs! don't really know why, but don't care either..